name: CI

on:
  push:
    paths:
      - 'networkinfra/**'
  pull_request:
    paths:
      - 'networkinfra/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check TF fmt
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'
      - run: |
          cd networkinfra/terraform/environments/dev || true
          terraform fmt -check || true
