name: Network Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: Housing-Intelligence/hi-platform-cicd/.github/workflows/terraform-apply.yml@main

    with:
      target_repository: Housing-Intelligence/hi-network-infra
      terraform_directory: terraform/environments
      aws_region: us-east-2
      environment: dev
      vpc_cidr: 10.0.0.0/16

    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}